stages:
  transform:
    cmd: python src/Transform.py businesses.csv inspections.csv
    deps:
    - data/SFBusinesses
    - src/Transform.py
    params:
    - transform.column_sort_index
    outs:
    - data/output/
  explore:
    cmd: python src/Explore.py data/output/geolocated_rest.csv
    deps:
    - data/output
    - src/Explore.py
    outs:
    - data/figures
    - data/statistics
  discretize:
    cmd: python src/Discretize.py geolocated_rest.csv
    deps:
    - data/output
    - src/Discretize.py
    outs:
    - data/discrete
