stages:
  transform:
    cmd: python src/Transform.py businesses.csv inspections.csv
    deps:
    - data/SFBusinesses
    - src/Transform.py
    params:
    - transform.column_sort_index
    outs:
    - data/output/
  explore:
    cmd: python src/Explore.py data/output/geolocated_rest.csv
    deps:
    - data/output
    - src/Explore.py
    outs:
    - data/figures
    - data/statistics
  discretize:
    cmd: python src/Discretize.py geolocated_rest.csv
    deps:
    - data/output
    - src/Discretize.py
    outs:
    - data/discrete
  evaluate:
    cmd: python src/Evaluate.py geolocated_rest.csv geolocated_rest_discretized.csv
    deps:
    - data/discrete
    - data/output
    - src/Evaluate.py
    outs:
    - data/evaluate
  detailed_evaluate:
    cmd: python src/Detailed_evaluate.py geolocated_rest.csv most_recent_inspections_statistics.json
    deps:
    - data/output
    - data/statistics
    - src/Detailed_evaluate.py
    outs:
    - data/det_evaluate
  iterate:
    cmd: python src/Iterate.py violations_plus.csv geolocated_rest.csv
    deps:
    - data/SFFoodProgram_Complete_Data
    - data/output
    - src/Iterate.py
    outs:
    - data/top_offenses
    - data/violation_hist
    - data/violation_hist_perfect
    - data/violations_scores
